version: '3'

services:
 
  mysql:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=rundeck
    volumes:
      - dbdata:/var/lib/mysql
      #- ./dockers/mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    expose:
      - 9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
    command: server /data
    volumes:
      - ./logdata:/data
    ports:
      - "9000:9000"
  minio-mc:
    image: minio/mc
    links:
    - minio
    entrypoint: /bin/sh
    command: -c 'sleep 10 && mc config host add docker http://minio:9000 minio miniosecret && mc mb -p docker/logs1'
  rundeck1:
    hostname: rundeck1
    # image: rundeckpro/enterprise:${RDVERS:-SNAPSHOT}
    build: ./
    links:
      - mysql
      - minio
    environment:
      - RUNDECK_NODE=rundeck1
      - RUNDECK_GRAILS_URL=http://localhost:4442
      - RUNDECK_SERVER_UUID=0b5440b7-4ab7-4f83-8f45-dddea83a1f5c
      - RUNDECK_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - RUNDECK_DATABASE_URL=jdbc:mysql://mysql/rundeck?autoReconnect=true&useUnicode=yes&useSSL=false
      - RUNDECK_DATABASE_USERNAME=rundeck
      - RUNDECK_DATABASE_PASSWORD=rundeck
      - RUNDECK_SECURITY_DBLOGIN_ENABLED=true
      - RUNDECK_SECURITY_DBLOGIN_CREATEADMINUSERANDROLES=true
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME=com.rundeck.rundeckpro.amazon-s3
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET=logs1
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION=us-east-1
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ENDPOINT=http://minio:9000/
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE=true
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ALLOWDELETE=true
      - TZ=America/Los_Angeles
    volumes:
      - ./realm.properties:/home/rundeck/server/config/realm.properties
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
    ports:
      - "4442:4440"
  rundeck2:
    hostname: rundeck2
    # image: rundeckpro/enterprise:${RDVERS:-SNAPSHOT}
    build: ./
    links:
      - mysql
      - minio
    environment:
      - RUNDECK_NODE=rundeck2
      - RUNDECK_GRAILS_URL=http://localhost:4441
      - RUNDECK_SERVER_UUID=DB6ADE59-95FF-4EE5-AC20-400E43171136
      - RUNDECK_DATABASE_DRIVER=com.mysql.jdbc.Driver
      - RUNDECK_DATABASE_URL=jdbc:mysql://mysql/rundeck?autoReconnect=true&useUnicode=yes&useSSL=false
      - RUNDECK_DATABASE_USERNAME=rundeck
      - RUNDECK_DATABASE_PASSWORD=rundeck
      - RUNDECK_SECURITY_DBLOGIN_ENABLED=true
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME=com.rundeck.rundeckpro.amazon-s3
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET=logs1
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION=us-east-1
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ENDPOINT=http://minio:9000/
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE=true
      - RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ALLOWDELETE=true
      - TZ=America/Los_Angeles
    volumes:
      - ./realm.properties:/home/rundeck/server/config/realm.properties
      - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
    ports:
      - "4441:4440"

volumes:
  logs:
  resources:
  tests:
  dbdata:
  logdata:


